// Put cryptocurrency status to "KO" to make it appear in a banner in LL
// You must specify a `message` and a `link` if "KO"
//
// Don't forget to increment the corresponding `nonce`, it is used
// to differenciate a new banner from a dismissed banner (user can
// click on banner to hide it permanently)

module.exports = [
  { id: "aion", status: "OK", message: "", link: "", nonce: 0 },
  { id: "akroma", status: "OK", message: "", link: "", nonce: 0 },
  { id: "ark", status: "OK", message: "", link: "", nonce: 0 },
  { id: "atheios", status: "OK", message: "", link: "", nonce: 0 },
  { id: "banano", status: "OK", message: "", link: "", nonce: 0 },
  { id: "bitcoin", status: "OK", message: "", link: "", nonce: 0 },
  { id: "bitcoin_cash", status: "OK", message: "", link: "", nonce: 0 },
  { id: "bitcoin_gold", status: "OK", message: "", link: "", nonce: 0 },
  { id: "bitcoin_private", status: "OK", message: "", link: "", nonce: 0 },
  { id: "callisto", status: "OK", message: "", link: "", nonce: 0 },
  { id: "clubcoin", status: "OK", message: "", link: "", nonce: 0 },
  { id: "dash", status: "OK", message: "", link: "", nonce: 0 },
  { id: "digibyte", status: "OK", message: "", link: "", nonce: 0 },
  { id: "dogecoin", status: "OK", message: "", link: "", nonce: 0 },
  { id: "ellaism", status: "OK", message: "", link: "", nonce: 0 },
  { id: "eos", status: "OK", message: "", link: "", nonce: 0 },
  { id: "eos_classic", status: "OK", message: "", link: "", nonce: 0 },
  { id: "ethereum", status: "OK", message: "", link: "", nonce: 0 },
  { id: "ethereum_classic", status: "OK", message: "", link: "", nonce: 0 },
  { id: "ether1", status: "OK", message: "", link: "", nonce: 0 },
  { id: "ethergem", status: "OK", message: "", link: "", nonce: 0 },
  { id: "ethersocial", status: "OK", message: "", link: "", nonce: 0 },
  { id: "expanse", status: "OK", message: "", link: "", nonce: 0 },
  { id: "gochain", status: "OK", message: "", link: "", nonce: 0 },
  { id: "hcash", status: "OK", message: "", link: "", nonce: 0 },
  { id: "icon", status: "OK", message: "", link: "", nonce: 0 },
  { id: "iota", status: "OK", message: "", link: "", nonce: 0 },
  { id: "komodo", status: "OK", message: "", link: "", nonce: 0 },
  { id: "litecoin", status: "OK", message: "", link: "", nonce: 0 },
  { id: "lisk", status: "OK", message: "", link: "", nonce: 0 },
  { id: "monero", status: "OK", message: "", link: "", nonce: 0 },
  { id: "musicoin", status: "OK", message: "", link: "", nonce: 0 },
  { id: "nano", status: "OK", message: "", link: "", nonce: 0 },
  { id: "neo", status: "OK", message: "", link: "", nonce: 0 },
  { id: "nimiq", status: "OK", message: "", link: "", nonce: 0 },
  { id: "ontology", status: "OK", message: "", link: "", nonce: 0 },
  { id: "particl", status: "OK", message: "", link: "", nonce: 0 },
  { id: "peercoin", status: "OK", message: "", link: "", nonce: 0 },
  { id: "pirl", status: "OK", message: "", link: "", nonce: 0 },
  { id: "pivx", status: "OK", message: "", link: "", nonce: 0 },
  { id: "poa", status: "OK", message: "", link: "", nonce: 0 },
  { id: "poswallet", status: "OK", message: "", link: "", nonce: 0 },
  { id: "qtum", status: "OK", message: "", link: "", nonce: 0 },
  { id: "ripple", status: "OK", message: "", link: "", nonce: 0 },
  { id: "stratis", status: "OK", message: "", link: "", nonce: 0 },
  { id: "stealthcoin", status: "OK", message: "", link: "", nonce: 0 },
  { id: "stellar", status: "OK", message: "", link: "", nonce: 0 },
  { id: "tezos", status: "OK", message: "", link: "", nonce: 0 },
  { id: "tron", status: "OK", message: "", link: "", nonce: 0 },
  { id: "ubiq", status: "OK", message: "", link: "", nonce: 0 },
  { id: "vechain", status: "OK", message: "", link: "", nonce: 0 },
  { id: "vertcoin", status: "OK", message: "", link: "", nonce: 0 },
  { id: "viacoin", status: "OK", message: "", link: "", nonce: 0 },
  { id: "wanchain", status: "OK", message: "", link: "", nonce: 0 },
  { id: "waves", status: "OK", message: "", link: "", nonce: 0 },
  { id: "zcash", status: "OK", message: "", link: "", nonce: 0 },
  { id: "zcoin", status: "OK", message: "", link: "", nonce: 0 },
  { id: "zencash", status: "OK", message: "", link: "", nonce: 0 },
  { id: "bitcoin_testnet", status: "OK", message: "", link: "", nonce: 0 },
  { id: "ethereum_testnet", status: "OK", message: "", link: "", nonce: 0 }
];
